In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
! pwd

/Users/emilioaguiar/code/LeWagon_Project/fedegiallorosso/solar_forecasting/notebooks


In [17]:
X = np.load('../raw_data/X_train_copernicus.npz', allow_pickle=True)


In [18]:
X.files

['datetime', 'GHI', 'CLS', 'SZA', 'SAA']

In [59]:
date = X['datetime']
SZA = X['SZA']
SSA = X['SAA']

In [81]:
print(f'zenith angles has this shape {SZA.shape}')
print(f'solar azimuth angle (SAA) has this shape {SSA.shape}')

zenith angles has this shape (1845, 8, 81, 81)
solar azimuth angle (SAA) has this shape (1845, 8, 81, 81)


In [82]:
print('First day of observation')
print(f'This is the shape of date {date.shape}')
date[0:4]


First day of observation
This is the shape of date (1845,)


array([datetime.datetime(2012, 1, 1, 9, 15),
       datetime.datetime(2012, 1, 1, 11, 15),
       datetime.datetime(2012, 1, 1, 13, 15),
       datetime.datetime(2012, 1, 1, 15, 15)], dtype=object)

In [114]:
print(f'SZA first observation has this shape {SZA[0,0].shape}')

SZA first observation has this shape (81, 81)


### Observation time: t-45

In [113]:
print(date[0])
SZA[0,0]

2012-01-01 09:15:00


array([[127.36, 127.38, 127.4 , ..., 129.17, 129.2 , 129.22],
       [127.35, 127.38, 127.4 , ..., 129.17, 129.19, 129.22],
       [127.35, 127.37, 127.4 , ..., 129.17, 129.19, 129.21],
       ...,
       [127.11, 127.14, 127.16, ..., 128.89, 128.91, 128.94],
       [127.11, 127.13, 127.16, ..., 128.89, 128.91, 128.93],
       [127.11, 127.13, 127.15, ..., 128.88, 128.9 , 128.93]])

### Observation time: t-30

In [116]:
print(date[1])
SZA[1,0]

2012-01-01 11:15:00


array([[151.09, 151.12, 151.15, ..., 153.52, 153.55, 153.58],
       [151.08, 151.12, 151.15, ..., 153.51, 153.54, 153.58],
       [151.08, 151.11, 151.14, ..., 153.51, 153.54, 153.57],
       ...,
       [150.63, 150.67, 150.7 , ..., 153.08, 153.11, 153.14],
       [150.63, 150.66, 150.69, ..., 153.07, 153.1 , 153.14],
       [150.62, 150.65, 150.68, ..., 153.07, 153.1 , 153.13]])

### Observation time: t-15

In [118]:
print(date[2])
SZA[2,0]

2012-01-01 13:15:00


array([[181.14, 181.18, 181.21, ..., 183.91, 183.94, 183.98],
       [181.14, 181.18, 181.21, ..., 183.91, 183.94, 183.98],
       [181.14, 181.18, 181.21, ..., 183.91, 183.94, 183.98],
       ...,
       [181.17, 181.2 , 181.24, ..., 183.99, 184.02, 184.06],
       [181.17, 181.2 , 181.24, ..., 183.99, 184.03, 184.06],
       [181.17, 181.2 , 181.24, ..., 183.99, 184.03, 184.06]])

### Observation time: t

In [119]:
print(date[3])
SZA[3,0]

2012-01-01 15:15:00


array([[210.88, 210.91, 210.94, ..., 213.2 , 213.23, 213.26],
       [210.88, 210.91, 210.94, ..., 213.21, 213.24, 213.27],
       [210.89, 210.92, 210.95, ..., 213.21, 213.24, 213.27],
       ...,
       [211.34, 211.37, 211.4 , ..., 213.67, 213.7 , 213.73],
       [211.35, 211.38, 211.41, ..., 213.68, 213.71, 213.74],
       [211.35, 211.38, 211.41, ..., 213.68, 213.71, 213.74]])

### Observation time: t+15

In [120]:
print(date[4])
SZA[4,0]

2012-01-02 09:15:00


array([[127.22, 127.24, 127.26, ..., 129.04, 129.06, 129.08],
       [127.22, 127.24, 127.26, ..., 129.03, 129.06, 129.08],
       [127.21, 127.24, 127.26, ..., 129.03, 129.05, 129.08],
       ...,
       [126.98, 127.  , 127.02, ..., 128.75, 128.77, 128.8 ],
       [126.97, 127.  , 127.02, ..., 128.75, 128.77, 128.79],
       [126.97, 126.99, 127.01, ..., 128.74, 128.77, 128.79]])

### Observation time: t+30

In [121]:
print(date[5])
SZA[5,0]

2012-01-02 11:15:00


array([[150.95, 150.98, 151.01, ..., 153.37, 153.4 , 153.44],
       [150.94, 150.97, 151.  , ..., 153.37, 153.4 , 153.43],
       [150.93, 150.96, 151.  , ..., 153.36, 153.39, 153.43],
       ...,
       [150.49, 150.52, 150.55, ..., 152.93, 152.96, 152.99],
       [150.48, 150.51, 150.54, ..., 152.92, 152.96, 152.99],
       [150.47, 150.51, 150.54, ..., 152.92, 152.95, 152.98]])

### Observation time: t+45

In [122]:
print(date[6])
SZA[6,0]

2012-01-02 13:15:00


array([[181.02, 181.05, 181.09, ..., 183.79, 183.82, 183.86],
       [181.02, 181.05, 181.09, ..., 183.79, 183.82, 183.86],
       [181.02, 181.05, 181.09, ..., 183.79, 183.83, 183.86],
       ...,
       [181.04, 181.08, 181.11, ..., 183.87, 183.9 , 183.94],
       [181.04, 181.08, 181.11, ..., 183.87, 183.91, 183.94],
       [181.04, 181.08, 181.11, ..., 183.87, 183.91, 183.94]])

### Observation time: t+60

In [123]:
print(date[7])
SZA[7,0]

2012-01-02 15:15:00


array([[210.81, 210.84, 210.87, ..., 213.14, 213.17, 213.2 ],
       [210.82, 210.85, 210.88, ..., 213.15, 213.18, 213.21],
       [210.82, 210.85, 210.88, ..., 213.15, 213.18, 213.21],
       ...,
       [211.28, 211.31, 211.34, ..., 213.61, 213.64, 213.67],
       [211.28, 211.31, 211.34, ..., 213.62, 213.65, 213.68],
       [211.29, 211.32, 211.35, ..., 213.63, 213.66, 213.69]])

2012-01-03 09:15:00


array([[127.08, 127.1 , 127.12, ..., 128.89, 128.92, 128.94],
       [127.07, 127.1 , 127.12, ..., 128.89, 128.91, 128.94],
       [127.07, 127.09, 127.12, ..., 128.89, 128.91, 128.93],
       ...,
       [126.84, 126.86, 126.88, ..., 128.61, 128.63, 128.66],
       [126.83, 126.85, 126.88, ..., 128.61, 128.63, 128.65],
       [126.83, 126.85, 126.87, ..., 128.6 , 128.62, 128.65]])

### Questions on the data set 
#### 1. What is the meaning of the value inside of the matrix 
#### 